version: '2'
networks:
  de_db: 
    driver: bridge

services:
  backend:
    build:
      dockerfile: df.prod
    extends: 
      file: dc.base.yml
      service: backend
    image: deb:production
    container_name: ${APP_NAME}
    environment:
      NODE_ENV: "production"
    ports:
      - "${PORT}:3000"
    networks:
      - de_db
